# Generated by Django 5.1.6 on 2025-03-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProyecto', '0002_categorias_categorias_proyecto_miembros_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='descripcion',
        ),
    ]
