# Generated by Django 5.1.6 on 2025-03-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProyecto', '0003_remove_proyectos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='fecha_vencimiento',
        ),
    ]
