# Generated by Django 5.1.6 on 2025-03-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProyecto', '0004_remove_tareas_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='id_proyecto',
        ),
    ]
