# Generated by Django 5.1.6 on 2025-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProyecto', '0005_remove_tareas_id_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias_proyecto',
            name='indice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
